from .import views
from django.urls import path

urlpatterns = [
	path('', views.home, name="home_page"),
	path('students/', views.students_view, name="students_list"),
	path('students/<int:id>/', views.students_list_view, name="students_list_view"),
	path('students/add/', views.add_student, name="add_student"),
	path('users/del<int:id>/', views.delete_user, name="delete_user"),
	path('parents/', views.parents_view, name="parents_list"),
	path('parents/add/', views.add_parent, name="add_parent"),
	path('teachers/', views.teachers_view, name="teachers_list"),
	path('teachers/add/', views.add_teacher, name="add_teacher"),
	path('class/', views.class_view, name="class_list"),
	path('class/add/', views.add_class, name="add_class"),
	path('class/del<int:id>/', views.delete_class, name="delete_class"),
	path('subject/', views.subjects_view, name="subjects_list"),
	path('subject/add/', views.add_subject, name="add_subject"),
	path('subject/del<int:id>/', views.delete_subject, name="delete_subject"),
	path('subject-allocation/', views.assign_teacher_view, name="assign_teacher_list"),
	path('subject-allocation/del<int:id>/', views.delete_all_allocated_subjects, name="delete_all_allocated_subjects"),
	path('subject-allocation/add/', views.add_assign_teacher, name="add_assign_teacher"),
	path('section-allocation/', views.section_allocation, name="section_allocation"),
	path('section-allocation/add/', views.add_section_allocation, name="add_assign_section"),
	path('section-allocation/del<int:id>/', views.delete_section_allocation, name="del_section_allocation"),
	path('section/', views.section_view, name="sections_list"),
	path('section/add/', views.add_section, name="add_section"),
	path('section/del<int:id>/', views.delete_section, name="delete_section"),
	path('attendance/', views.attendance_list, name="attendance_list"),
	path('attendance/add/', views.add_attendance, name="add_attendance"),
	path('attendance/del<int:id>/', views.delete_attendance, name="delete_attendance"),
	path('score_entry/', views.score_list, name="score_list"),
	path('score_entry/add/', views.score_entry, name="score_entry"),
	path('api/chart/', views.expenditure_graph, name="expense_graph_url"),
	]