# Generated by Django 2.2.9 on 2020-01-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_card_template_name', models.CharField(max_length=50)),
                ('transcript_template_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_attendance_info', models.BooleanField(default=True)),
                ('show_class_vg', models.BooleanField(default=True)),
                ('show_final_avg', models.BooleanField(default=True)),
                ('show_final_grade', models.BooleanField(default=True)),
                ('show_final_position', models.BooleanField(default=True)),
                ('show_class_name', models.BooleanField(default=True)),
                ('show_highest_total', models.BooleanField(default=True)),
                ('show_lowest_total', models.BooleanField(default=True)),
                ('show_school_motto', models.BooleanField(default=True)),
                ('show_number_in_class', models.BooleanField(default=True)),
                ('show_next_term_begin', models.BooleanField(default=True)),
                ('show_no_student_col', models.BooleanField(default=True)),
                ('show_student_id', models.BooleanField(default=True)),
                ('show_student_picture', models.BooleanField(default=True)),
                ('show_total_score', models.BooleanField(default=True)),
                ('form_teacher_lbl', models.CharField(max_length=100)),
                ('guiding_n_concil_lbl', models.CharField(max_length=100)),
                ('overall_comment_lbl', models.CharField(max_length=100)),
                ('show_form_teacher_com', models.BooleanField(default=True)),
                ('show_extra_comment', models.BooleanField(default=True)),
                ('show_guiding_n_council_com', models.BooleanField(default=True)),
                ('show_promotion_status', models.BooleanField(default=True)),
                ('use_auto_comment', models.BooleanField(default=False)),
                ('result_decimal_places', models.IntegerField(default=2)),
                ('show_class_avg_for_subject_col', models.BooleanField(default=True)),
                ('show_remark_column', models.BooleanField(default=True)),
                ('show_previous_term_info', models.BooleanField(default=True)),
                ('show_subject_lowes_col', models.BooleanField(default=True)),
                ('show_percent_symbol', models.BooleanField(default=True)),
                ('show_grade_column', models.BooleanField(default=True)),
                ('show_subject_position', models.BooleanField(default=True)),
                ('use_ordinal_position', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.Section')),
            ],
        ),
    ]
