# Generated by Django 2.2.4 on 2019-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Delivered'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(related_name='childrens', to='sms.Student'),
        ),
    ]
