# Generated by Django 2.1.5 on 2019-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
