# Generated by Django 2.1.5 on 2019-01-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='in_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Class'),
        ),
    ]
