# Generated by Django 2.2.4 on 2019-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_expense_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sms_unit',
            field=models.IntegerField(default=200),
        ),
    ]
