# Generated by Django 2.2.4 on 2019-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20190826_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(related_name='guardians', to='sms.Student'),
        ),
    ]
