# Generated by Django 2.1.5 on 2019-04-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20190221_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='business_phone1',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='business_phone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='social_link1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='social_link2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='social_link3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
