# Generated by Django 2.1.5 on 2019-02-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20190207_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Student'),
            preserve_default=False,
        ),
    ]
