# Generated by Django 2.1.5 on 2019-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20190428_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='school_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
