# Generated by Django 2.1.5 on 2019-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190201_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_late_for',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
