# Generated by Django 2.1.5 on 2019-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190207_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
