# Generated by Django 2.1.5 on 2019-02-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190201_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Student'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='in_class',
        ),
        migrations.AddField(
            model_name='subject',
            name='in_class',
            field=models.ManyToManyField(to='sms.Class'),
        ),
    ]
