# Generated by Django 2.1.5 on 2019-02-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190207_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Session'),
            preserve_default=False,
        ),
    ]
