# Generated by Django 2.1.5 on 2019-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20190201_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='in_class',
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(to='sms.Subject'),
        ),
    ]
