# Generated by Django 2.1.5 on 2019-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_payment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='teller_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
