# Generated by Django 2.1.5 on 2019-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_payment_teller_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='amount_to_pay',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
