# Generated by Django 2.1.5 on 2019-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_class_amount_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='original_amount',
        ),
    ]
