# Generated by Django 2.1.5 on 2019-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20190202_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='subjectassign',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectassign',
            name='subject',
            field=models.ManyToManyField(to='sms.Subject'),
        ),
    ]
