# Generated by Django 2.1.5 on 2019-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_remove_payment_original_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='amount_to_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
