# Generated by Django 2.1.5 on 2019-02-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20190203_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectassign',
            old_name='subject',
            new_name='subjects',
        ),
    ]
