# Generated by Django 2.1.5 on 2019-02-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20190207_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassign',
            name='clss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Class'),
            preserve_default=False,
        ),
    ]
