# Generated by Django 2.1.5 on 2019-02-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_subjectassign_clss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='sms.Student'),
        ),
    ]
