# Generated by Django 2.1.5 on 2019-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_auto_20190208_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=250)),
            ],
        ),
    ]
