# Generated by Django 2.1.5 on 2019-02-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=12)),
                ('rank', models.CharField(max_length=5)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='ft_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ft_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='school_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='school_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='school_slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='st_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='st_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tt_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tt_ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
