# Generated by Django 2.1.5 on 2019-02-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_auto_20190209_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
