# Generated by Django 2.1.5 on 2019-02-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_auto_20190210_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='fca',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sca',
            field=models.FloatField(default=0),
        ),
    ]
