# Generated by Django 2.1.5 on 2019-02-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_auto_20190210_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='cumulative',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
