# Generated by Django 2.2.9 on 2020-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.IntegerField(default=500, verbose_name='Available Unit')),
                ('show_grade', models.BooleanField(default=True, verbose_name='Show Grade')),
                ('show_position', models.BooleanField(default=True, verbose_name='Show Position')),
                ('show_promotion_status', models.BooleanField(default=False, verbose_name='Show promotion status')),
                ('sms_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Prefix')),
                ('sms_suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Suffix')),
                ('sender_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Sender ID')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notifications Setting',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=10, verbose_name='To User')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='Date Send')),
                ('body', models.CharField(max_length=250, verbose_name='Body')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Delivered'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Send Notification',
                'verbose_name_plural': 'Send Notifications',
            },
        ),
    ]
