# Generated by Django 2.2.9 on 2020-01-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.IntegerField(default=500, verbose_name='Available Unit')),
                ('show_grade', models.BooleanField(default=True, verbose_name='Show Grade')),
                ('show_position', models.BooleanField(default=True, verbose_name='Show Position')),
                ('show_promotion_status', models.BooleanField(default=False, verbose_name='Show promotion status')),
                ('sms_prefix', models.CharField(default='', max_length=20, verbose_name='SMS Prefix')),
                ('sms_suffix', models.CharField(default='', max_length=20, verbose_name='SMS Suffix')),
                ('sender_id', models.CharField(default='', max_length=20, verbose_name='SMS Sender ID')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notifications Setting',
            },
        ),
        migrations.DeleteModel(
            name='SMS_Configuration',
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'Send Notification', 'verbose_name_plural': 'Send Notifications'},
        ),
    ]
