# Generated by Django 2.2.9 on 2020-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notification', '0002_auto_20200103_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='sender_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Sender ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sms_prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Prefix'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sms_suffix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SMS Suffix'),
        ),
    ]
