# Generated by Django 2.1.5 on 2019-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(max_length=10)),
                ('student_fname', models.CharField(max_length=20)),
                ('student_lname', models.CharField(max_length=20)),
                ('student_oname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('address', models.CharField(max_length=200)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity')], max_length=13)),
                ('date_of_birth', models.DateTimeField()),
                ('clss', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ImageField(upload_to='admission/')),
            ],
        ),
    ]
