# Generated by Django 2.2.4 on 2019-08-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Session'),
        ),
    ]
