# Generated by Django 2.2.3 on 2019-07-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='phone',
            new_name='applicant_phone_no',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='clss',
            new_name='student_clss',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='date_of_birth',
            new_name='student_dob',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='gender',
            new_name='student_gender',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='passport',
            new_name='student_passport',
        ),
        migrations.RenameField(
            model_name='onlineadmission',
            old_name='religion',
            new_name='student_religion',
        ),
    ]
