# Generated by Django 2.2.3 on 2019-07-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_setting_school_town'),
        ('frontend', '0002_auto_20190707_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Session'),
            preserve_default=False,
        ),
    ]
