# Generated by Django 2.2.3 on 2019-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_onlineadmission_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadmission',
            name='status',
            field=models.CharField(default='Waiting', max_length=20),
        ),
    ]
