# Generated by Django 2.2.4 on 2019-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_site_su',
            field=models.BooleanField(default=False),
        ),
    ]
