# Generated by Django 2.2.4 on 2019-08-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_site_su',
        ),
    ]
