# Generated by Django 2.2.4 on 2019-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
    ]
