# Generated by Django 2.2.9 on 2019-12-31 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subjects',
        ),
        migrations.AddField(
            model_name='batch',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='subjects',
            field=models.ManyToManyField(to='sms.Subject'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 30, 33, 997299), verbose_name='closes on'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 30, 33, 997217), verbose_name='opens from'),
        ),
    ]
