# Generated by Django 2.2.9 on 2019-12-31 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20191231_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepermission',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 31, 1, 880445), verbose_name='closes on'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 31, 1, 880398), verbose_name='opens from'),
        ),
    ]
