# Generated by Django 2.2.9 on 2020-01-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_grade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='score'),
        ),
    ]
