# Generated by Django 2.2.9 on 2019-12-31 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20191231_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='amount_to_pay',
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 20, 18, 14, 451510), verbose_name='closes on'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 20, 18, 14, 451454), verbose_name='opens from'),
        ),
    ]
