# Generated by Django 2.2.9 on 2019-12-31 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20191231_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepermission',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 19, 35, 919068, tzinfo=utc), verbose_name='closes on'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 19, 19, 35, 919027, tzinfo=utc), verbose_name='opens from'),
        ),
    ]
