# Generated by Django 2.2.9 on 2020-01-01 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20191231_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Student Class', 'verbose_name_plural': 'Student classes'},
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='closes on'),
        ),
        migrations.AlterField(
            model_name='scorepermission',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='opens from'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sms.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_of_admission', to='sms.Session', verbose_name='Session of Admission'),
        ),
    ]
