# Generated by Django 2.2.9 on 2020-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_auto_20200101_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markpercentage',
            name='name',
            field=models.CharField(max_length=10, verbose_name='name'),
        ),
    ]
