# Generated by Django 2.2.9 on 2020-01-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20200103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='next_of_kin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.TeacherNok'),
        ),
    ]
