# Generated by Django 2.2.9 on 2020-01-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20200103_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='user',
        ),
    ]
