# Generated by Django 2.2.9 on 2020-01-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_auto_20200103_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachernok',
            old_name='othername',
            new_name='other_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
    ]
