# Generated by Django 2.2.9 on 2020-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_auto_20200103_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernok',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachernok',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
