# Generated by Django 2.2.9 on 2020-01-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_auto_20200103_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Next of kin'),
        ),
        migrations.DeleteModel(
            name='TeacherNok',
        ),
    ]
