# Generated by Django 2.2.9 on 2020-01-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_auto_20200103_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.Section', verbose_name='Section'),
        ),
    ]
