# Generated by Django 2.2.9 on 2020-01-04 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0016_teacher_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100, verbose_name='placeholder')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='section_signatures/', verbose_name='signature')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Section', verbose_name='section')),
                ('section_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='section head')),
            ],
            options={
                'verbose_name': 'section allocation',
                'verbose_name_plural': 'section allocations',
            },
        ),
        migrations.RenameModel(
            old_name='SubjectAssign',
            new_name='SubjectAllocation',
        ),
        migrations.DeleteModel(
            name='SectionAssign',
        ),
    ]
