# Generated by Django 2.2.9 on 2020-01-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_auto_20200104_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Batch', verbose_name='batch'),
            preserve_default=False,
        ),
    ]
