# Generated by Django 2.2.9 on 2020-01-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_subjectallocation_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionallocation',
            name='section_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Teacher', verbose_name='section head'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Teacher', verbose_name='teacher'),
        ),
    ]
