# Generated by Django 2.2.9 on 2020-01-06 18:19

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='School name')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('active_until', models.DateField()),
                ('school_package', models.CharField(choices=[('Starter', 'Starter'), ('Regular', 'Regular'), ('Ultimate', 'Ultimate')], default='Ultimate', max_length=20, verbose_name='Package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='schools.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
