# Generated by Django 2.2.9 on 2020-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='School name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='school_package',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Regular', 'Regular'), ('Ultimate', 'Ultimate')], default='Ultimate', max_length=20, verbose_name='Package'),
        ),
    ]
